### ISSUE TITLE
Error finding transcribe.sh

### ISSUE THREAD

**Issue by xSidewinderx** [CrimeIsDown/trunk-transcribe#15]
Im having issues with Trunk Recording finding the the transcribe.sh file? I have placed it in the root directory of trunk recorder, where my config.json sits. I get this message in the terminal when running thought
"sh: 1: transcribe.sh: not found"

Part of my config.json
"audiostreaming": true,
        "audioArchive": true,
        "callLog": true,
        "uploadScript": "transcribe.sh",
        "dailyLog": true,
        "modulation": "qpsk"

**Comment by EricTendian** [comment]
Hi @xSidewinderx, sorry I'm just now seeing this. Can you try using an absolute path to the upload script, or alternatively add `./` at the beginning so it treats it as a relative path? Right now I think it is treating it like a regular Linux command so it can't find it.

**Comment by EricTendian** [comment]
Going to close this, but please open again if you still need help.
